### ISSUE TITLE
Automatically starting NervesHubLink.Supervisor race condition

### ISSUE THREAD

**Issue by coop** [nerves-hub/nerves_hub_link#11]
In the switch from NervesHub to NervesHubLink the `NervesHubLink.Supervisor` is automatically started on boot instead of "whenever I want to start it". This change has introduced a race condition in my code because my `NervesHubLink.Client` relies on a process that may not have been started yet. Obviously I can catch the exception and reschedule the update but I'm wondering why the change?

This change also takes away the ability to conditionally include the supervisor which is something I do in development all the time when I'm testing without pushing releases.

**Comment by jjcarstens** [comment]
A few things:
1. I'm definitely unaware of all the use-cases and totally missed this one that you might be relying on
2. When I think of hardware uptime and reliability, ability to update firmware at any time to remove bad firmware is really high priority which means trying to do everything possible to keep that connection alive and independent of application logic. i.e. If you manage the NervesHub supervisor in your app, but its totally borked and can't start, now it cannot connect to NervesHub to get _not_-broken firmware. One of the simplest elixir mechanisms is to put that in its own app with separate supervision and start it independent of the app process, like via `shoehorn`. Or even just having the application outside of your application might be enough.
3. A race condition is bad and we shouldn't allow to break this process. Either handling in your app, or adding a bit to nerves_hub_link to recover from errors and keep trying to get updates
4. Ability to reduce noise in tests is a great thing. We should fix that and reduce trying to connect to something externally during tests

**Comment by jjcarstens** [comment]
I think one way we could address this issue is by allowing the library to start its own supervision, or be included manually in external supervision. Much like how [`nerves_ssh`](https://github.com/nerves-project/nerves_ssh/blob/main/lib/nerves_ssh/application.ex#L26-L33) handles this deduction

**Comment by joshk** [comment]
With the `connect: false` config option you can control when and where the children are added and started.

It's not perfect by any means, and I'd be happy to look into this if this feature is still wanted, but as its been 3.5 years since any activity on this issue, I think its best to close it for the time being.
