### ISSUE TITLE
Dokumentation on using nerves hub link without nerves key are outdated

### ISSUE THREAD

**Issue by LostKobrakai** [nerves-hub/nerves_hub_link#134]
Documentation still refers to phoenix_client, which has long been replaced with slipstream afaik.

**Comment by gabrielmancini** [comment]
there is some walk throw for this integration, i am feeling lost about the certs process... 
kind of article/issue/forum like "put nerves-hub in production and link your first firmware for OTA step-by-step"?

**Comment by joshk** [comment]
Hi @LostKobrakai , could you please point us to the documentation in question and we will update this?

**Comment by LostKobrakai** [comment]
@joshk seems like you already removed the parts mentioning phoenix_client in https://github.com/nerves-hub/nerves_hub_link/commit/8ffaa9c02ba30de33629a3e7f42e3fada79828ac
