### ISSUE TITLE
Report FWUP version to NervesHub

### ISSUE THREAD

**Issue by Mrjaco12** [nerves-hub/nerves_hub_link#43]
In [certain scenarios](https://github.com/nerves-hub/nerves_hub_web/issues/538) it makes sense for NervesHub to know what version of FWUP a device is running this means FWUP needs to report this data in it's communications with the NervesHub back end.

**Comment by Mrjaco12** [comment]
@fhunleth @mobileoverlord I'm creating this issue to track adding the FWUP version here and, I assume, we'll also need it in [the http version](https://github.com/nerves-hub/nerves_hub_link_http). I figured this would be a good place to discuss the approach since you guys have much greater familiarity with the whole Nerves/NervesHub ecosystem than I do.

After a first inspection, my first idea was to just grab the version from fwup via `System.cmd` and insert it around [the time we grab other meta data from the runtime KV](https://github.com/nerves-hub/nerves_hub_link/blob/426dcd64a32af4a3e658ba6a1824cd3bdd865f9c/lib/nerves_hub_link/configurator.ex#L51). Does that make sense or is there some point, before or after, that would work better?

**Comment by fhunleth** [comment]
I like your idea.

**Comment by jjcarstens** [comment]
Released in https://github.com/nerves-hub/nerves_hub_link/releases/tag/v0.9.1
