### ISSUE TITLE
Support `window_size` from NervesHub

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_link#46]
`extty` supports changing the window size of the remote console via [`ExTTY.window_change/3`](https://hexdocs.pm/extty/ExTTY.html#window_change/3)

The [ConsoleChannel](https://github.com/nerves-hub/nerves_hub_link/blob/main/lib/nerves_hub_link/console_channel.ex#L26) docs show that `window_size` is an optional message from the Server, but it doesn't actually have a matching `handle_info` clause to handle that message, so it needs to be added.

Also, this would be the counterpart to https://github.com/nerves-hub/nerves_hub_web/issues/654

**Comment by honsq90** [comment]
i can give this a go
